BLOCK_BREAK: false
BLOCK_PLACE: false
DROP_ITEM: false
PICKUP_ITEM: false
ENTITY_EXPLODE: false
BLOCK_EXPLODE: false
FIRE_DAMAGE: false
FOOD_LEVEL_CHANGE: false
ICE_MELT: false
ITEM_DAMAGE: false
LEAVE_DECAY: false
LINGERING_POTION_SPLASH: false
POTION_SPLASH: false
SWAP_HANDS: false
CORAL_DIE: false
BlockedCommands: []
BlockIntractableBlocks:
  - BREWING_STAND
  - DISPENSER
  - DROPPER
  - ANVIL
  - CHIPPED_ANVIL
  - DAMAGED_ANVIL
  - HOPPER
  - NOTE_BLOCK
  - FURNACE
  - DAYLIGHT_DETECTOR
  - FLOWER_POT
  - OBSERVER
  - DRAGON_EGG
  - LEVER
  - TRAPPED_CHEST
  - CHEST
  - ENDER_CHEST
  - TNT
  - CRAFTING_TABLE
  - COMPARATOR
  - JUKEBOX
  - ENCHANTING_TABLE
  - BEACON
  - SHULKER_BOX
  - BLACK_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - LIME_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - PINK_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - RED_SHULKER_BOX
  - WHITE_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - BLACK_BED
  - BLUE_BED
  - BROWN_BED
  - CYAN_BED
  - GRAY_BED
  - LIGHT_BLUE_BED
  - LIGHT_GRAY_BED
  - LIME_BED
  - MAGENTA_BED
  - ORANGE_BED
  - PINK_BED
  - PURPLE_BED
  - RED_BED
  - WHITE_BED
  - YELLOW_BED
  - OAK_TRAPDOOR
  - ACACIA_TRAPDOOR
  - BIRCH_TRAPDOOR
  - DARK_OAK_TRAPDOOR
  - JUNGLE_TRAPDOOR
  - SPRUCE_TRAPDOOR
  - CRIMSON_TRAPDOOR
  - WARPED_TRAPDOOR
  - MANGROVE_TRAPDOOR
  - SPRUCE_FENCE_GATE
  - ACACIA_FENCE_GATE
  - BIRCH_FENCE_GATE
  - DARK_OAK_FENCE_GATE
  - OAK_FENCE_GATE
  - WARPED_FENCE_GATE
  - JUNGLE_FENCE_GATE
  - MANGROVE_FENCE_GATE
  - CRIMSON_FENCE_GATE
  - STONE_BUTTON
  - SPRUCE_BUTTON
  - OAK_BUTTON
  - JUNGLE_BUTTON
  - DARK_OAK_BUTTON
  - BIRCH_BUTTON
  - ACACIA_BUTTON
  - MANGROVE_BUTTON
  - WARPED_BUTTON
  - CRIMSON_BUTTON
  - ACACIA_DOOR
  - WARPED_DOOR
  - BIRCH_DOOR
  - DARK_OAK_DOOR
  - JUNGLE_DOOR
  - CRIMSON_DOOR
  - SPRUCE_DOOR
  - OAK_DOOR
  - MANGROVE_DOOR
  - DRAGON_EGG
  - LOOM
  - BARREL
  - SMOKER
  - BLAST_FURNACE
  - CARTOGRAPHY_TABLE
  - FLETCHING_TABLE
  - GRINDSTONE
  - SMITHING_TABLE
  - STONECUTTER
  - CAMPFIRE
  - COMPOSTER
  - BELL
  - LECTERN
BlockIntractableItems:
  - MINECART_CHEST
  - MINECART
  - MINECART_HOPPER
  - MINECART_FURNACE
  - ITEM_FRAME
  - GLOW_ITEM_FRAME
  - PAINTING
